
feature_engineering:
  TRAIN_TEST_SPLIT_RATIO: 0.2
  RANDOM_STATE: 42



# ====================== Data Transformation =======================

missing_cols:
  use:
    - dropna





add_columns:
  appeared_candidates:
    2016: 1128633
    2017: 1122351
    2018: 1043000
    2019: 1147125
    2020: 1023000
    2021: 939008
    2022: 905590
    2023: 1113325
    2024: 1415110
    2025: 1475103


hybrid_encode:
  columns:
    - Institute
    - Branch
   
  target:
    - Opening Rank
    - Closing Rank
  alpha: 10
  n_splits: 5
  random_state: 42

target_encode:
  columns:
    - Seat Type

  target:
    - Opening Rank
    - Closing Rank
  alpha: 10
  n_splits: 5
  random_state: 42  


one_hot_encode:
  columns:
    - Gender
    - Quota


drop_columns:
  - Academic Program Name
  - Institute
  - Branch
  - Seat Type
  - Gender
  - Quota



log_normalised_columns:
  - Opening Rank
  - Closing Rank
  - Institute_FreqEnc
  - Branch_FreqEnc
  - appeared_candidates

standarize_columns:
  - Institute_FreqEnc
  - Branch_FreqEnc
  - appeared_candidates
  - Institute_TargetEnc
  - Branch_TargetEnc
  - Seat Type_TargetEnc
  - Year
  - Round
  - Duration
  



